name:                order-graph
version:             0.1.0.0
homepage:            https://github.com/runeksvendsen/order-graph#readme
license:             BSD3
author:              Rune K. Svendsen
maintainer:          runesvend@gmail.com
copyright:           CC0
category:            value

default-extensions:
- FlexibleContexts
- DeriveGeneric
- DataKinds
- PolyKinds

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -O2
  - -fno-ignore-asserts
  - -Wall

library:
  source-dirs: src
  dependencies:
    - protolude
    - orderbook
    - primitive
    - deepseq
    - hashable
    - pretty-show
    - text
    - aeson
    - bellman-ford
    - vector
    - thrist
    - tagged
    - text
    - safe-money

executables:
  order-graph-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
    - protolude
    - orderbook
    - order-graph
    - bellman-ford
    - logging
    - unliftio
    - unordered-containers
    - safe-money
    - vector
    - criterion
    - aeson
    - directory
    - optparse-applicative
    - filepath
    - cassava
    - text-format
    - text

tests:
  order-graph-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - order-graph
    - vector
    - HUnit
    - hspec-expectations
    - hspec-expectations-pretty-diff
    - QuickCheck
    - hspec
    - tasty
    - tasty-smallcheck
    - tasty-quickcheck
    - smallcheck
    - hspec-smallcheck
    - random-shuffle
    - text
    - safe-money
    - orderbook
    - bellman-ford

benchmarks:
  order-graph-bench:
    main:                Main.hs
    source-dirs:
    - bench
    dependencies:
    - order-graph
    - gauge
